grammar com.ghvandoorn.xtext.statemachine.Dsl with org.eclipse.xtext.common.Terminals

generate dsl "http://www.ghvandoorn.com/xtext/statemachine/Dsl"

StateMachine:
	{StateMachine}
	('events'
		(events+=Event)+
	'end')?
	'initial_state' initialState=[State]
	states+=State*;

State:
	'state' name=ID
		transitions+=Transition*
	'end';

Transition:
	event=[Event] '=>' state=[State];

Event:
	name=ID;
