/*
 * generated by Xtext
 */
package com.ghvandoorn.xtext.statemachine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends com.ghvandoorn.xtext.statemachine.AbstractDslRuntimeModule {

}
